export const SET_QUESTION_LOADING_FLAG = 'SET_QUESTION_LOADING_FLAG';

export const SET_QUESTION = 'SET_QUESTION';
export const SET_SUBJECTS = 'SET_SUBJECTS';
export const SET_INFORMATION = 'SET_INFORMATION';
export const SET_CONSTRAINTS = 'SET_CONSTRAINTS';
export const SET_ANSWERS = 'SET_ANSWERS';
